components:
  schemas:
    Band:
      type: object
      required:
        - title
        - length
        - albumId
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        title:
          type: string
          description: Required. 255 characters of fewer.
          maxLength: 255
          example: Minha nova track
        trackNumber:
          type: integer
          example: 1
          description: Required. Positive integer.
          nullish: true
        length:
          type: integer
          example: 10
          description: Required. Positive integer.
        albumId:
          type: integer
          example: 1
          description: Required. Positive integer.
            