paths:
  /api/tracks:
    get:
      tags:
        - Tracks
      summary: List Tracks
      description: List all tracks.
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Track"
    post:
      tags:
        - Tracks
      summary: Create track
      description: Create and return a track.
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Track"
      responses:
        201:
          description: CREATED
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Band"
        400:
          $ref: "#/components/responses/BadRequest"