paths:
  /api/tracks:
    get:
      tags:
        - Tracks
      summary: List tracks
      description: List all tracks.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Track"
    post:
      tags:
        - Tracks
      summary: Create track
      description: Create and return a track.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Track"
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        400:
          $ref: "#/components/responses/BadRequest"
  /api/tracks/{trackId}:
    get:
      tags:
        - Tracks
      parameters:
        - title: trackId
          in: path
          description: Track id for retrieve.
          required: true
          schema:
            type: integer
      summary: Retrieve a track
      description: Retrieve a track by id.
      reponses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        404:
          $ref: "#/components/responses/NotFound"

